# Generated by Django 6.0.1 on 2026-05-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhãn hiệu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name_plural': 'Nhãn Hiệu',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name_plural': 'Danh Mục',
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_percent', models.FloatField(default=0, verbose_name='Chiết khấu (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
            ],
            options={
                'verbose_name_plural': 'Nhóm Khách Hàng',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng ban')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name_plural': 'Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phương thức')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
            ],
            options={
                'verbose_name_plural': 'Phương Thức Thanh Toán',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cửa hàng')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('opening_hours', models.CharField(blank=True, default='9:00 - 22:00', max_length=255, verbose_name='Giờ mở cửa')),
                ('warehouse_info', models.TextField(blank=True, verbose_name='Thông tin kho')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name_plural': 'Cửa Hàng',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung ứng')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Người liên hệ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('tax_code', models.CharField(blank=True, max_length=50, verbose_name='Mã số thuế')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name_plural': 'Nhà Cung Ứng',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=100, verbose_name='Họ')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Điểm tích lũy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='dashboard.customergroup', verbose_name='Nhóm khách hàng')),
            ],
            options={
                'verbose_name_plural': 'Khách Hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=100, verbose_name='Họ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ')),
                ('hire_date', models.DateField(verbose_name='Ngày tuyển dụng')),
                ('salary', models.FloatField(default=0, verbose_name='Lương')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='dashboard.department', verbose_name='Phòng ban')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='dashboard.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name_plural': 'Nhân Viên',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Số phiếu nhập')),
                ('receipt_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập')),
                ('total_amount', models.FloatField(default=0, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee', verbose_name='Người tạo')),
            ],
            options={
                'verbose_name_plural': 'Phiếu Nhập Hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Mã đơn hàng online')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Địa chỉ giao hàng')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại giao hàng')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Số đơn hàng')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đã giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('total_amount', models.FloatField(default=0, verbose_name='Tổng tiền')),
                ('discount', models.FloatField(default=0, verbose_name='Chiết khấu')),
                ('tax_amount', models.FloatField(default=0, verbose_name='Thuế')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee', verbose_name='Người tạo')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='dashboard.customer', verbose_name='Khách hàng')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người đặt (online)')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name_plural': 'Đơn Hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Số tiền')),
                ('status', models.CharField(choices=[('pending', 'Chưa thanh toán'), ('partial', 'Thanh toán một phần'), ('completed', 'Đã thanh toán')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Mã tham chiếu')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thanh toán')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.order', verbose_name='Đơn hàng')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.paymentmethod', verbose_name='Phương thức thanh toán')),
            ],
            options={
                'verbose_name_plural': 'Thanh Toán',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã vạch')),
                ('cost_price', models.FloatField(verbose_name='Giá vốn')),
                ('sale_price', models.FloatField(verbose_name='Giá bán')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Tồn kho hiện tại')),
                ('min_stock', models.IntegerField(default=10, verbose_name='Tồn kho tối thiểu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dashboard.brand', verbose_name='Nhãn hiệu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name_plural': 'Sản Phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_cost', models.FloatField(verbose_name='Đơn giá')),
                ('total_cost', models.FloatField(verbose_name='Thành tiền')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.goodsreceipt', verbose_name='Phiếu nhập')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Chi Tiết Phiếu Nhập',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='Số PO')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Ngày giao dự kiến')),
                ('total_amount', models.FloatField(default=0, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('received', 'Đã nhận'), ('cancelled', 'Hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to='dashboard.employee', verbose_name='Người duyệt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to='dashboard.employee', verbose_name='Người tạo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='dashboard.store', verbose_name='Cửa hàng')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='dashboard.supplier', verbose_name='Nhà cung ứng')),
            ],
            options={
                'verbose_name_plural': 'Đơn Mua Hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt', to='dashboard.purchaseorder', verbose_name='Đơn mua'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='dashboard.supplier', verbose_name='Nhà cung ứng'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, verbose_name='Thông tin kho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='dashboard.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name_plural': 'Kho',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('import', 'Nhập hàng'), ('export', 'Xuất hàng'), ('adjust', 'Điều chỉnh'), ('return', 'Trả hàng')], max_length=20, verbose_name='Loại chuyển động')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='Tham chiếu')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee', verbose_name='Người tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='dashboard.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='dashboard.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name_plural': 'Chuyển Động Kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='dashboard.warehouse', verbose_name='Kho'),
        ),
        migrations.CreateModel(
            name='WarehouseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('import', 'Nhập hàng'), ('export', 'Xuất hàng')], max_length=20, verbose_name='Loại phiếu')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='Số phiếu')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Nhà cung ứng/Người nhận')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('total_amount', models.FloatField(default=0, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('is_printed', models.BooleanField(default=False, verbose_name='Đã in')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian in')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee', verbose_name='Người tạo')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='dashboard.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name_plural': 'Phiếu Nhập/Xuất Kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.FloatField(verbose_name='Đơn giá')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.warehousebatch', verbose_name='Phiếu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Chi Tiết Phiếu Nhập/Xuất',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.FloatField(verbose_name='Đơn giá')),
                ('total_price', models.FloatField(verbose_name='Thành tiền')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='dashboard.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Chi Tiết Đơn Hàng',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(verbose_name='Số lượng đặt')),
                ('unit_price', models.FloatField(verbose_name='Đơn giá')),
                ('total_price', models.FloatField(verbose_name='Thành tiền')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Sản phẩm')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.purchaseorder', verbose_name='Đơn mua')),
            ],
            options={
                'verbose_name_plural': 'Chi Tiết Đơn Mua',
                'unique_together': {('purchase_order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField(default=0, verbose_name='Tồn kho hiện tại')),
                ('quantity_reserved', models.IntegerField(default=0, verbose_name='Tồn kho dự trữ')),
                ('last_counted_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần kiểm kho cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='dashboard.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='dashboard.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name_plural': 'Tồn Kho',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
