# Generated by Django 6.0.1 on 2026-05-05 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Họ tên người nhận'),
        ),
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ người dùng'),
        ),
        migrations.AddField(
            model_name='order',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ người dùng'),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài viết')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Nội dung bài viết')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Tóm tắt')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Hình ảnh nổi bật')),
                ('external_link', models.URLField(blank=True, verbose_name='Liên kết bài viết bên ngoài')),
                ('source_type', models.CharField(choices=[('manual', 'Tự viết'), ('word', 'Từ Word'), ('external', 'Từ liên kết')], default='manual', max_length=20, verbose_name='Nguồn bài viết')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
            ],
            options={
                'verbose_name_plural': 'Bài viết trang giới thiệu',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Tiểu sử')),
                ('website', models.URLField(blank=True, verbose_name='Website cá nhân')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác thực')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Người dùng VIP')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Điểm tích lũy')),
                ('preferred_language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='vi', max_length=10, verbose_name='Ngôn ngữ ưu tiên')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Thông báo email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Thông báo SMS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP đăng nhập cuối')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thông tin người dùng',
                'verbose_name_plural': 'Thông tin người dùng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Hình ảnh')),
                ('category', models.CharField(choices=[('promotion', 'Khuyến mãi'), ('event', 'Sự kiện'), ('product', 'Sản phẩm mới'), ('company', 'Tin công ty'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Danh mục')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Đã lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tin nổi bật')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
            ],
            options={
                'verbose_name_plural': 'Tin tức',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Điểm đánh giá')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Phản hồi của cửa hàng')),
                ('admin_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phản hồi')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.orderitem', verbose_name='Món trong đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-created_at'],
                'unique_together': {('order_item', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='Hình ảnh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.review', verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name_plural': 'Hình ảnh đánh giá',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('unit', models.CharField(default='cái', max_length=50, verbose_name='Đơn vị')),
                ('min_quantity', models.IntegerField(default=10, verbose_name='Tồn kho tối thiểu')),
                ('unit_price', models.FloatField(default=0, verbose_name='Giá nhập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name_plural': 'Sản Phẩm Kho',
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('import', 'Nhập hàng'), ('export', 'Xuất hàng')], max_length=20, verbose_name='Loại giao dịch')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.FloatField(default=0, verbose_name='Đơn giá')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Nhà cung ứng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giao dịch')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.warehouseitem', verbose_name='Sản phẩm kho')),
            ],
            options={
                'verbose_name_plural': 'Giao Dịch Kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Đánh giá tổng thể')),
                ('food_quality', models.IntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Chất lượng món ăn')),
                ('service_quality', models.IntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Chất lượng dịch vụ')),
                ('delivery_speed', models.IntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Tốc độ giao hàng')),
                ('packaging_quality', models.IntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Chất lượng đóng gói')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung đánh giá')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Phản hồi của cửa hàng')),
                ('admin_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phản hồi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='dashboard.order', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name_plural': 'Đánh giá đơn hàng',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'user')},
            },
        ),
    ]
