# Generated by Django 6.0.1 on 2026-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_full_name_order_lat_order_lng_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ZenMart', max_length=200, verbose_name='Tên website')),
                ('intro_text', models.TextField(blank=True, default='Có câu hỏi hoặc góp ý? Chúng tôi luôn sẵn sàng lắng nghe!', verbose_name='Lời giới thiệu')),
                ('email', models.TextField(blank=True, default='1250080068@sv.hcmunre.edu.vn\n1250080065@sv.hcmunre.edu.vn\n1250080110@sv.hcmunre.edu.vn', verbose_name='Email nhận liên hệ (mỗi dòng 1 email)')),
                ('phone', models.CharField(blank=True, default='1900-xxxx', max_length=100, verbose_name='Hotline')),
                ('address', models.TextField(blank=True, default='TP. Hồ Chí Minh, Việt Nam', verbose_name='Địa chỉ')),
                ('working_hours', models.CharField(blank=True, default='Tất cả các ngày: 8:00 - 22:00', max_length=200, verbose_name='Giờ làm việc')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_user', models.CharField(blank=True, default='duongdanhuy25@gmail.com', max_length=200, verbose_name='SMTP Email gửi')),
                ('smtp_password', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP App Password')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Sử dụng TLS')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Cài đặt Liên hệ',
            },
        ),
    ]
