# Generated by Django 6.0.1 on 2026-05-12 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time_slot',
            field=models.CharField(blank=True, max_length=50, verbose_name='Khung giờ giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='nearest_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to='dashboard.store', verbose_name='Cửa hàng giao hàng gần nhất'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Khoảng cách giao hàng (km)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.FloatField(default=0, verbose_name='Phí giao hàng'),
        ),
    ]
