# Generated by Django 6.0.4 on 2026-05-13 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_order_delivery_time_slot_order_nearest_store_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.FloatField(default=0, verbose_name='Số tiền giảm giá'),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mã giảm giá')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed', 'Cố định')], default='percentage', max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá trị đơn hàng tối thiểu')),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giảm giá tối đa')),
                ('usage_limit', models.IntegerField(blank=True, null=True, verbose_name='Giới hạn số lần sử dụng')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Số lần đã sử dụng')),
                ('user_limit', models.IntegerField(default=1, verbose_name='Giới hạn sử dụng mỗi user')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động'), ('expired', 'Hết hạn')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee', verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Mã Giảm Giá',
                'verbose_name_plural': 'Mã Giảm Giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.discountcode', verbose_name='Mã giảm giá'),
        ),
        migrations.CreateModel(
            name='DiscountCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền giảm')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian sử dụng')),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='dashboard.discountcode', verbose_name='Mã giảm giá')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='dashboard.order', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Lịch Sử Sử Dụng Mã Giảm Giá',
                'verbose_name_plural': 'Lịch Sử Sử Dụng Mã Giảm Giá',
                'ordering': ['-used_at'],
                'unique_together': {('discount_code', 'user', 'order')},
            },
        ),
    ]
