# Generated by Django 6.0.4 on 2026-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_order_discount_amount_discountcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
